-- Generated by Galactic decompiler .gg/qy2neXET6W

if game.PlaceId ~= 11040063484 then
	if game.PlaceId ~= 11542692507 then
		if game.PlaceId ~= 12289293395 then
			game.Players.LocalPlayer:Kick('It seems that we do not support that game, check our discord to get games that we support.')
		else
			loadstring(game:HttpGet('https://raw.githubusercontent.com/XLinestX/ShinyTool-V3/main/BoxingFightersSimulator.lua'))()
		end
	else
		loadstring(game:HttpGet('https://raw.githubusercontent.com/XLinestX/ShinyTool-V3/main/AnimeSoulsSimulator.lua'))()
	end
else
	loadstring(game:HttpGet('https://raw.githubusercontent.com/XLinestX/ShinyTool-V3/main/SwordFigthersSimulator.lua'))()
end