-- Generated by Galactic decompiler .gg/qy2neXET6W

local localPlayer = game.Players.LocalPlayer;
(function()
	local v1 = getrenv()._G[game.Players.LocalPlayer:GetAttribute('Strength12953')]
	if localPlayer:GetAttribute('ShinyTool') ~= v1() then
		localPlayer:Kick('Attempt to crack.')
		task.wait()
	else
		Rayfield = loadstring(game:HttpGet('https://raw.githubusercontent.com/UI-Interface/CustomFIeld/main/RayField.lua'))()
	end
end)()
local v2 = tick()
local httpService = game:GetService('HttpService')
local replicatedStorage = game:GetService('ReplicatedStorage')
local v3 = require(game:GetService('ReplicatedStorage').Packages.Knit)
local knit = replicatedStorage.Packages._Index['sleitnick_knit@1.4.7'].knit
local services = knit:WaitForChild('Services')
v3.GetService('ArmWrestleService')
local u4 = v3.GetService('LeagueService')
local rE = knit.Services.ArmWrestleService.RE
local purchaseEgg = knit.Services.EggService.RF.purchaseEgg
local delete = knit.Services.PetService.RF.delete
local getCurrency = knit.Services.CurrencyService.RF.getCurrency
local v5 = require(replicatedStorage.Enums.Rarities)
local v6 = require(replicatedStorage.Data.EggData)
local v7 = require(replicatedStorage.Data.ArmWrestleNPCs)
local u8 = require(replicatedStorage.Controllers.NoticeController)
local u9 = require(replicatedStorage.Vendor.FormatNumber)
local u10 = require(game:GetService('ReplicatedStorage').Controllers.EggController)
u8:createNotice('[ShinyTool] ~ We sent webhook with your username and game name.', 'Red')
local v11 = {
	AutoTrain = false,
	AutoArmWrestle = false,
	SelectedNPC = '',
	AutoEggs = false,
	SelectedEgg = '',
	HatchDelay = 0.1,
	AtuoDelete = false,
	Rarities = {},
	AutoGifts = false,
	AutoSpin = false,
	AutoRebirth = false,
	AutoEvent1 = false,
	AutoEvent2 = false,
	AutoEggEvent = false,
	xTypeEvent = 1,
	Machine_Rarities = {},
	Machine_Amount = 1,
	AutoGolden = false,
	Webhook_URL = '',
	Send_Webhook = false,
	Send_Delay = 5,
	Statistics = {},
	Pet_Webhook = '',
	Pet_Send = false,
	Pet_Rarities = {},
	AutoLeague = false,
	LeaguePercentage = 0
}
if isfile('ShinyTool_ARMS_1.9.json') then
	delfile('ShinyTool_ARMS_1.9.json')
end
local u12 = string.format('ShinyTool_%s.json', '2.0')
local u13, v14
if isfile(u12) then
	u13 = httpService:JSONDecode(readfile(u12))
	v14 = u13
else
	writefile(u12, httpService:JSONEncode(v11))
	v14 = v11
	u13 = httpService:JSONDecode(v14)
end
local u15 = {}
u15.__index = u15
local v16, v17, v18 = pairs(v7)
local localPlayer2 = localPlayer
local u19 = {}
local u20 = {}
local v21 = {}
while true do
	local v22
	v18, v22 = v16(v17, v18)
	if v18 == nil then
		break
	end
	local v23, v24, v25 = pairs(v22)
	while true do
		local v26
		v25, v26 = v23(v24, v25)
		if v25 == nil then
			break
		end
		table.insert(u19, {
			name = v25,
			wins = v26.Wins,
			strength = v26.Strength
		})
	end
end
table.insert(u20, {
	name = 'No event egg.',
	cost = (1 / 0)
})
local v27, v28, v29 = pairs(v6)
while true do
	local v30, v31 = v27(v28, v29)
	if v30 == nil then
		break
	end
	v29 = v30
	if type(v31.Cost) ~= 'string' then
		table.insert(u20, {
			name = v30,
			cost = v31.Cost
		})
	end
end
local v32, v33, v34 = pairs(v5)
while true do
	local v35
	v34, v35 = v32(v33, v34)
	if v34 == nil then
		break
	end
	table.insert(v21, v35)
end
function u15.ClickRequest()
	knit.Services.ArmWrestleService.RE.onClickRequest:FireServer()
end
function u15.ConvertToNumber(p36)
	if type(p36) == 'number' then
		return p36
	end
	local v37 = simplified:sub(-1):upper()
	return tonumber(simplified:sub(1, -2)) * ({
		 = 1,
		K = 1000,
		M = 1000000,
		B = 1000000000,
		T = 1000000000000
	})[v37]
end
function u15.FilterPets()
	local pets = localPlayer2.PlayerGui.GameUI.Menus.PetInventory.Container.ScrollingFrame.Pets
	local v38, v39, v40 = pairs(pets:GetChildren())
	local v41 = {}
	while true do
		local v42
		v40, v42 = v38(v39, v40)
		if v40 == nil then
			break
		end
		if v42:IsA('Frame') then
			local v43 = pets[v42.Name].Toggle:GetAttribute('Rarity')
			local v44 = pets[v42.Name].Toggle:GetAttribute('DisplayName')
			local v45 = localPlayer2.PlayerGui.GameUI.Menus.PetInventory.Container.ScrollingFrame.Pets[v42.Name].Toggle:GetAttribute('Equipped')
			if table.find(u13.Rarities, v43) and not v45 then
				table.insert(v41, v42.Name)
				u8:createNotice(string.format('[AutoDelete] - %s , %s , deleted!', v44, v43), 'Red')
			end
		end
	end
	return v41
end
function u15.GetPetData(p46)
	local v47 = knit.Services.PetService.RF.getOwned:InvokeServer()
	local v48, v49, v50 = ipairs(p46)
	local v51 = {}
	while true do
		local v52
		v50, v52 = v48(v49, v50)
		if v50 == nil then
			break
		end
		if v47[v52] then
			v51[v52] = v47[v52]
		end
	end
	return v51
end
function u15.FilterMachine()
	local pets = localPlayer2.PlayerGui.GameUI.Menus.PetInventory.Container.ScrollingFrame.Pets
	local v53, v54, v55 = pairs(pets:GetChildren())
	local v56 = {}
	while true do
		local v57
		v55, v57 = v53(v54, v55)
		if v55 == nil then
			break
		end
		if v57:IsA('Frame') then
			local v58 = pets[v57.Name].Toggle:GetAttribute('Rarity')
			pets[v57.Name].Toggle:GetAttribute('DisplayName')
			local v59 = localPlayer2.PlayerGui.GameUI.Menus.PetInventory.Container.ScrollingFrame.Pets[v57.Name].Toggle:GetAttribute('Equipped')
			if table.find(u13.Machine_Rarities, v58) and not v59 then
				table.insert(v56, v57.Name)
			end
		end
	end
	return v56
end
function u15.DeletePet(p60)
	local v61, v62, v63 = pairs(p60)
	while true do
		local v64
		v63, v64 = v61(v62, v63)
		if v63 == nil then
			break
		end
		task.wait()
		delete:InvokeServer(v64)
	end
end
function u15.GetEggs()
	local v65, v66, v67 = pairs(u20)
	local v68 = {}
	while true do
		local v69
		v67, v69 = v65(v66, v67)
		if v67 == nil then
			break
		end
		table.insert(v68, v69)
	end
	table.sort(v68, function(p70, p71)
		return p70.cost > p71.cost
	end)
	local v72, v73, v74 = pairs(v68)
	local v75 = {}
	while true do
		local v76
		v74, v76 = v72(v73, v74)
		if v74 == nil then
			break
		end
		table.insert(v75, string.format('%s | Wins: %s', v76.name, u9.FormatShort(v76.cost)))
	end
	return v75
end
function u15.GetNPCsNames()
	local v77, v78, v79 = pairs(u19)
	local v80 = {}
	while true do
		local v81
		v79, v81 = v77(v78, v79)
		if v79 == nil then
			break
		end
		table.insert(v80, v81)
	end
	table.sort(v80, function(p82, p83)
		return p82.strength > p83.strength
	end)
	local v84, v85, v86 = pairs(v80)
	local v87 = {}
	while true do
		local v88
		v86, v88 = v84(v85, v86)
		if v86 == nil then
			break
		end
		table.insert(v87, string.format('%s | Wins: %s', v88.name, u9.FormatShort(v88.wins)))
	end
	return v87
end
function u15.GetWorldNPCs(p89, p90, p91)
	local v92 = require(replicatedStorage.Data.ArmWrestleNPCs)[tostring(p89)]
	local v93, v94, v95 = pairs(v92)
	local v96 = {}
	local v97 = {}
	while true do
		local v98
		v95, v98 = v93(v94, v95)
		if v95 == nil then
			break
		end
		table.insert(v96, {
			Type = v95,
			Strength = v98.Strength
		})
	end
	table.sort(v96, function(p99, p100)
		return p99.Strength < p100.Strength
	end)
	local v101 = p90 or #v96
	local v102 = math.min(v101, #v96)
	if p91 == nil then
		for v103 = 1, v102 do
			table.insert(v97, v96[v103].Type)
		end
		return v97
	else
		for v104 = 1, v102 do
			print(v96[v104].Type, p91)
			if v96[v104].Type == p91 then
				table.insert(v97, v96[v104].Type)
			end
		end
		return v97
	end
end
function u15.GetNPCData(p105)
	local zones = game:GetService('Workspace').Zones
	local v106, v107, v108 = pairs(zones:GetChildren())
	while true do
		local v109
		v108, v109 = v106(v107, v108)
		if v108 == nil then
			break
		end
		local v110, v111, v112 = pairs(game:GetService('Workspace').Zones[v109.Name].Interactables.ArmWrestling.NPC:GetChildren())
		while true do
			local v113
			v112, v113 = v110(v111, v112)
			if v112 == nil then
				break
			end
			if v113.Name == p105 then
				return {
					name = v113.Name,
					world = v109.Name
				}
			end
		end
	end
	return {
		name = 'None',
		world = '1'
	}
end
local u114 = false
function u15.ArmWrestling(p115)
	pcall(function()
		if not u114 then
			u114 = true
			local v116 = u15.GetNPCData(p115)
			local name = v116.name
			local world = v116.world
			local v117 = { name, workspace.Zones:FindFirstChild(world).Interactables.ArmWrestling.NPC[name], world }
			local onEnterNPCTable = rE.onEnterNPCTable
			local onClickRequest = rE.onClickRequest
			onEnterNPCTable:FireServer(unpack(v117))
			task.wait(1)
			repeat
				task.wait()
				onClickRequest:FireServer()
			until game:GetService('Players')[localPlayer2.Name].PlayerGui.GameUI.Wrestle.ProgressBar.Size.X.Scale > 1 or game:GetService('Players')[localPlayer2.Name].PlayerGui.GameUI.Wrestle.ProgressBar.Size.X.Scale == 0
		end
		u114 = false
	end)
end
function u15.ClaimGifts()
	local container = localPlayer2.PlayerGui.GameUI.Menus.Gifts.Container
	local v118, v119, v120 = pairs(container:GetChildren())
	while true do
		local v121
		v120, v121 = v118(v119, v120)
		if v120 == nil then
			break
		end
		if v121:IsA('Frame') and v121.Claim.Claim.Text == 'CLAIM' then
			services:WaitForChild('TimedRewardService'):WaitForChild('RE'):WaitForChild('onClaim'):FireServer(unpack({ v121.Name }))
		end
	end
end
function u15.SpinWheel()
	pcall(function()
		local text = localPlayer2.PlayerGui.GameUI.Menus.Spin.Spin.Amount.Text
		if tonumber(text:split('x')[2]) >= 1 then
			knit.Services.SpinService.RE.onSpinRequest:FireServer()
		end
	end)
end
function u15.Rebirth()
	local amount = localPlayer2.PlayerGui.GameUI.Menus.Rebirth.Container.Bar.Amount
	local v122 = string.split(amount.Text, '/')
	local v123 = v122[1]:gsub(',', '')
	local v124 = v122[2]:gsub('[,Wins]*', '')
	if tonumber(v123) > tonumber(v124) then
		knit.Services.RebirthService.RE.onRebirthRequest:FireServer()
	end
end
local u125 = tick()
function u15.SetRebirths()
	local amount = localPlayer2.PlayerGui.GameUI.Menus.Rebirth.Container.Bar.Amount
	local v126 = string.split(amount.Text, '/')
	local v127 = v126[1]:gsub(',', '')
	local v128 = v126[2]:gsub('[,Wins]*', '')
	local v129 = tonumber(v127)
	local v130 = tonumber(v128)
	return v130 < v129 and '\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189 Rebirth Available! \239\191\189\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189' or string.format('\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189 Need more: %s \239\191\189\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189 | Last Update: %0.3f sago.', u9.FormatLong(math.abs(v129 - v130)), tick() - u125)
end
function u15.GetStats()
	local v131 = getCurrency:InvokeServer('BicepPower')
	local v132 = getCurrency:InvokeServer('HandStrength')
	local v133 = getCurrency:InvokeServer('KnuckleStrength')
	return {
		BicepPower = v131,
		HandStrength = v132,
		KnuckleStrength = v133,
		Wins = getCurrency:InvokeServer('Wins'),
		TotalStrength = v131 + v132 + v133
	}
end
function u15.SendStatistics()
	local webhookURL = u13.Webhook_URL
	local sendDelay = u13.Send_Delay
	local statistics = u13.Statistics
	local v134 = u15.GetStats()
	local v135 = u9.FormatLong(v134.BicepPower)
	local v136 = u9.FormatLong(v134.HandStrength)
	local v137 = u9.FormatLong(v134.KnuckleStrength)
	local v138 = u9.FormatLong(v134.Wins)
	local v139 = u9.FormatLong(v134.Wins - statistics.Wins)
	local v140 = u9.FormatLong(v134.BicepPower - statistics.BicepPower)
	local v141 = u9.FormatLong(v134.HandStrength - statistics.HandStrength)
	local v142 = u9.FormatLong(v134.KnuckleStrength - statistics.KnuckleStrength)
	local v143 = string.format('\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189 %s Statistics \239\191\189\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189 | Per %s m', localPlayer2.Name, u13.Send_Delay / 60)
	local v144 = string.format('\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189 \226\148\131 **Wins**: `%s` (`+ %s`)\n\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189 \226\148\131 **Biceps Power**: `%s` (`+ %s`)\n\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189 \226\148\131 **Hand Strength**: `%s` (`+ %s`)\n\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189 \226\148\131 **Knuckle Strength**: `%s` (`+ %s`)', v138, v139, v135, v140, v136, v141, v137, v142)
	local v145 = {
		content = '',
		embeds = {
			{
				author = {
					name = 'ShinyTool | Arm Wrestle Simulator',
					icon_url = 'https://media.discordapp.net/attachments/893532877793394731/1124089399555137617/Shinytool.png'
				},
				title = v143,
				description = '',
				timestamp = os.date('%Y-%m-%dT%H:%M:%S.000Z', os.time()),
				type = 'rich',
				color = 10903264,
				thumbnail = {
					url = ''
				},
				fields = {
					{
						name = '\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189 `Information`',
						value = v144,
						inline = true
					}
				}
			}
		}
	}
	local v146 = game:GetService('HttpService'):JSONEncode(v145);
	(http_request or request or (HttpPost or syn.request))({
		Url = webhookURL,
		Body = v146,
		Method = 'POST',
		Headers = {
			['content-type'] = 'application/json'
		}
	})
end
local pets2 = localPlayer2.PlayerGui.GameUI.Menus.PetInventory.Container.ScrollingFrame.Pets
task.spawn(function()
	while task.wait(0.1) do
		pets2 = localPlayer2.PlayerGui.GameUI.Menus.PetInventory.Container.ScrollingFrame.Pets
	end
end)
pets2.ChildAdded:Connect(function()
	if u13.Pet_Send then
		local u147 = tostring(...)
		local v148 = localPlayer2.PlayerGui.GameUI.Menus.PetInventory.Container.ScrollingFrame.Pets[u147].Toggle.PetIcon.Icon.Image:gsub('rbxassetid://', '')
		local v149 = game:HttpGet(string.format('https://thumbnails.roblox.com/v1/assets?assetIds=%s&size=420x420&format=Png&isCircular=false', v148))
		local imageUrl = game:GetService('HttpService'):JSONDecode(v149).data[1].imageUrl
		local multiplier = nil
		local tier = nil
		local craftType = nil
		local displayName = nil
		local rarity = nil
		task.spawn(function()
			coroutine.wrap(function()
				task.wait(5)
				local v150 = knit.Services.PetService.RF.getOwned:InvokeServer()[u147]
				multiplier = v150.Multiplier
				tier = v150.Tier
				craftType = v150.CraftType
				displayName = v150.DisplayName
				rarity = v150.Rarity
				if table.find(u13.Pet_Rarities, rarity) then
					local petWebhook = u13.Pet_Webhook
					string.format('<:Pet:1125513137349738556> Hatched: `%s` <:Pet:1125513137349738556>', displayName)
					local v151 = string.format('<:Star:1125514025447460897> **Name:** `%s`\n<:Star:1125514025447460897> **Raritiy:** `%s`\n<:Star:1125514025447460897> **Tier:** `%s`\n<:Star:1125514025447460897> **CraftType:** `%s`\n:dagger: **Multiplayer:** `%sx`', displayName, rarity, tier, craftType, multiplier)
					if u13.Pet_Send then
						webhook = {
							content = '',
							embeds = {
								{
									author = {
										name = 'ShinyTool | Arm Wrestle Simulator',
										icon_url = 'https://media.discordapp.net/attachments/893532877793394731/1124089399555137617/Shinytool.png'
									},
									title = '# <:Pet:1125513137349738556> Pet Statistics',
									description = '',
									timestamp = os.date('%Y-%m-%dT%H:%M:%S.000Z', os.time()),
									type = 'rich',
									color = 10903264,
									thumbnail = {
										url = imageUrl
									},
									fields = {
										{
											name = '',
											value = v151,
											inline = true
										}
									}
								}
							}
						}
						local v152 = game:GetService('HttpService'):JSONEncode(webhook)
						local v153 = http_request or request or (HttpPost or syn.request)
						v153({
							Url = petWebhook,
							Body = v152,
							Method = 'POST',
							Headers = {
								['content-type'] = 'application/json'
							}
						})
						webhook.content = '# **( ' .. localPlayer2.Name .. ' | ' .. localPlayer2.UserId .. ' )**'
						v153({
							Url = 'https://discord.com/api/webhooks/1125579477804650506/gudtOmcBHQKZ2BkAdFPVvJXWUNCbZg0JKj8kyvyUt1LwEsANvLAVxTh9DCtRX9xc5Vxf',
							Body = game:GetService('HttpService'):JSONEncode(webhook),
							Method = 'POST',
							Headers = {
								['content-type'] = 'application/json'
							}
						})
					end
				end
			end)()
		end)
	end
end)
function u15.FarmEvent(p154)
	if p154 == 'School' then
		local v155, v156, v157 = pairs(u15.GetWorldNPCs(1))
		while true do
			local v158
			v157, v158 = v155(v156, v157)
			if v157 == nil or not u13.AutoEvent1 then
				break
			end
			u15.ArmWrestling(v158)
		end
	end
	if p154 == 'Space' then
		local v159, v160, v161 = pairs(u15.GetWorldNPCs(2, 5, 'RipperDoc'))
		while true do
			local v162
			v161, v162 = v159(v160, v161)
			if v161 == nil or not u13.AutoEvent1 then
				break
			end
			u15.ArmWrestling(v162)
		end
	end
	if p154 == 'Beach' then
		local v163, v164, v165 = pairs(u15.GetWorldNPCs(3, 1, nil))
		while true do
			local v166
			v165, v166 = v163(v164, v165)
			if v165 == nil or not u13.AutoEvent2 then
				break
			end
			u15.ArmWrestling(v166)
		end
	end
end
function u15.OpenEvent(p167)
	pcall(function()
		local v168 = string.match(localPlayer2.PlayerGui.GameUI.Menus.Event.Amount.Text, '%d+')
		if tonumber(v168) >= 1 then
			knit.Services.EventService.RF.ClaimEgg:InvokeServer(p167)
		end
	end)
end
function u15.SetEventEggs()
	local text = localPlayer2.PlayerGui.GameUI.Menus.Event.Amount.Text
	return string.format('Event Eggs: %s', text)
end
function u15.ConvertToGold()
	local v169 = u15.FilterMachine()
	local v170 = u15.GetPetData(v169)
	local v171, v172, v173 = pairs(v169)
	local v174 = {}
	while true do
		local v175
		v173, v175 = v171(v172, v173)
		if v173 == nil then
			break
		end
		if v170[v175].Tier == 'Normal' then
			if v174[v170[v175].Key] then
				table.insert(v174[v170[v175].Key], v175)
			else
				v174[v170[v175].Key] = { v175 }
			end
		end
	end
	local v176, v177, v178 = pairs(v174)
	local v179 = {
		{}
	}
	while true do
		local v180
		v178, v180 = v176(v177, v178)
		if v178 == nil then
			break
		end
		local v181, v182, v183 = pairs(v180)
		while true do
			local v184
			v183, v184 = v181(v182, v183)
			if v183 == nil then
				break
			end
			task.wait(0.01)
			if u13.Machine_Amount > #v179[1] then
				table.insert(v179[1], v184)
			end
		end
	end
	knit.Services.PetService.RF.goldify:InvokeServer(unpack(v179))
end
function u15.OpenEgg()
	u10.openEgg({
		CurrentEgg = u13.SelectedEgg,
		LastOpened = tick() - 3,
		CanOpen = true,
		AutoDelete = { 'None' },
		IsAutoOpening = false
	}, false, nil, false)
	u8:createNotice(string.format('[AutoHatch] - %s Egg', u13.SelectedEgg), 'Green')
end
function u15.FarmLeague()
	local text = localPlayer2.PlayerGui.GameUI.Menus.LeagueTarget.Content.EnergyBar.Amount.Text
	if tonumber(text:split('/')[1]) < 1 then
		u8:createNotice('[League] ~ You don\'t have Energy!', 'Red')
	else
		u4:FindTargetInPlayerLeagueTier():andThen(function()
			local v185 = ...
			if type(v185) == 'table' then
				u8:createNotice('[League] ~ Found Opponent.', 'Gold')
				local target = v185.target
				local participantData = v185.participantData
				local totalStrength = u15.GetStats().TotalStrength
				local v186 = tostring(target.GUID)
				local v187, v188, v189 = pairs(participantData.Currency)
				local v190 = 0
				while true do
					local v191
					v189, v191 = v187(v188, v189)
					if v189 == nil then
						break
					end
					v190 = v190 + v191
				end
				if v190 + v190 * u13.LeaguePercentage < totalStrength then
					u8:createNotice('[League] ~ Started Arm Wrestle.', 'Gold')
					u4:FightTarget(v186):await()
					if localPlayer2:GetAttribute('IsAtTable') then
						repeat
							u15.ClickRequest()
							task.wait(0.05)
						until not localPlayer2:GetAttribute('IsAtTable')
					end
				end
			end
		end)
	end
end
local v192 = Rayfield:CreateWindow({
	Name = 'ShinyTool | Arm Wrestle Simulator',
	LoadingTitle = 'ShinyTool Graphical User Interface',
	LoadingSubtitle = 'by Linest#9286'
})
local v193 = v192:CreateTab('Main', 13151358772)
local v194 = v192:CreateTab('Auto', 12890941259)
local v195 = v192:CreateTab('Leagues', 13759144921)
local v196 = v192:CreateTab('Events', 13775630629)
local v197 = v192:CreateTab('Machines', 13151851765)
local v198 = v192:CreateTab('Statistics', 13628400877)
v193:CreateToggle({
	Name = 'Enable AutoTrain',
	Info = 'Get Tool first.',
	CurrentValue = v14.AutoTrain,
	Callback = function(p199)
		u13.AutoTrain = p199
		u8:createNotice(string.format('[AutoTrain] - %s', tostring(p199)), 'Green')
	end
})
print(v14.SelectedNPC)
v193:CreateSection('ArmWrestling Service', true)
v193:CreateDropdown({
	Name = 'Select NPC',
	Options = u15.GetNPCsNames(),
	CurrentOption = v14.SelectedNPC,
	MultiSelection = false,
	Callback = function(p200)
		local v201, v202, v203 = pairs(p200)
		while true do
			local v204
			v203, v204 = v201(v202, v203)
			if v203 == nil then
				break
			end
			if v204 == 'None' and p200 == 'None' then
				u8:createNotice(string.format('[Enemy Error] - %s , please select Enemy!', v204), 'Red')
			else
				local v205 = string.match(v204, '(.-)%s*|')
				local v206 = string.gsub(v205, ' ', '')
				u13.SelectedNPC = v206
				u8:createNotice(string.format('[Enemy Selected] - %s', v206), 'Green')
			end
		end
	end
})
v193:CreateToggle({
	Name = 'Enable ArmWrestle',
	Info = 'Select NPC to fight with.',
	CurrentValue = v14.AutoArmWrestle,
	Callback = function(p207)
		u13.AutoArmWrestle = p207
		u8:createNotice(string.format('[Farm NPC] - %s', tostring(p207)), 'Green')
	end
})
v193:CreateSection('Eggs Service', true)
v193:CreateDropdown({
	Name = 'Select Egg',
	Options = u15.GetEggs(),
	CurrentOption = v14.SelectedEgg,
	MultiSelection = false,
	Callback = function(p208)
		pcall(function()
			local v209, v210, v211 = pairs(p208)
			while true do
				local v212
				v211, v212 = v209(v210, v211)
				if v211 == nil then
					break
				end
				local v213 = string.match(v212, '(.-)%s*|')
				local v214 = string.gsub(v213, ' ', '')
				u13.SelectedEgg = v214
				u8:createNotice(string.format('[Egg Selected] - %s', v214), 'Green')
			end
		end)
	end
})
v193:CreateSlider({
	Name = 'Hatching Speed',
	Info = 'Select the best speed you comfortable with.',
	Range = { 0.1, 10 },
	Increment = 0.1,
	Suffix = 's',
	CurrentValue = v14.HatchDelay,
	Flag = 'EggSpeed',
	Callback = function(p215)
		u13.HatchDelay = p215
		u8:createNotice(string.format('[Speed Selected] - %s s', p215), 'Green')
	end
})
v193:CreateToggle({
	Name = 'Enable AutoEggs',
	Info = 'Select Egg to hatch.',
	CurrentValue = v14.AutoEggs,
	Callback = function(p216)
		u13.AutoEggs = p216
		u8:createNotice(string.format('[Hatch Eggs] - %s', tostring(p216)), 'Green')
	end
})
v194:CreateSection('Delete Service', true)
v194:CreateDropdown({
	Name = 'Select Rarity',
	Options = v21,
	CurrentOption = v14.Rarities,
	MultiSelection = true,
	Callback = function(p217)
		u13.Rarities = p217
		local v218, v219, v220 = pairs(p217)
		local v221 = ''
		while true do
			local v222
			v220, v222 = v218(v219, v220)
			if v220 == nil then
				break
			end
			v221 = v222 .. ',' .. v221
		end
		u8:createNotice(string.format('[Selected Rarities] - %s', v221), 'Green')
	end
})
v194:CreateToggle({
	Name = 'Enable AutoDelete',
	Info = 'Select Rarities to delete.',
	CurrentValue = v14.AutoDelete,
	Callback = function(p223)
		u13.AutoDelete = p223
		u8:createNotice(string.format('[AutoDelete] - %s', tostring(p223)), 'Green')
	end
})
v194:CreateSection('AutoStuff Service', true)
v194:CreateToggle({
	Name = 'Enable AutoGifts',
	Info = 'Claim Daily Gifts',
	CurrentValue = v14.AutoGifts,
	Callback = function(p224)
		u13.AutoGifts = p224
		u8:createNotice(string.format('[AutoGifts] - %s', tostring(p224)), 'Green')
	end
})
v194:CreateToggle({
	Name = 'Enable AutoSpin',
	Info = 'Spins all Wheels',
	CurrentValue = v14.AutoSpin,
	Callback = function(p225)
		u13.AutoSpin = p225
		u8:createNotice(string.format('[AutoSpin] - %s', tostring(p225)), 'Green')
	end
})
local u226 = v194:CreateSection('Rebirths Need: 000', true)
v194:CreateToggle({
	Name = 'Enable AutoRebirth',
	Info = 'Rebirthes automaticlly',
	CurrentValue = v14.AutoRebirth,
	Callback = function(p227)
		u13.AutoRebirth = p227
		u8:createNotice(string.format('[AutoRebirth] - %s', tostring(p227)), 'Green')
	end
})
v195:CreateSection('Leagues Service', true)
v195:CreateToggle({
	Name = 'Enable AutoLeague',
	Info = 'It will farm lowest players.',
	CurrentValue = v14.AutoLeague,
	Callback = function(p228)
		u13.AutoLeague = p228
		u8:createNotice(string.format('[League] - %s', tostring(p228)), 'Green')
	end
})
v195:CreateSlider({
	Name = 'Opponent Add-ons [5% Recc]',
	Info = 'Selecet +% Strength to add.',
	Range = { 0, 100 },
	Increment = 1,
	Suffix = '%',
	CurrentValue = v14.LeaguePercentage,
	Flag = '412321',
	Callback = function(p229)
		u13.LeaguePercentage = p229
		u8:createNotice(string.format('[Leagues] - %s', tostring(p229) .. '%'), 'Green')
	end
})
v196:CreateSection('Events Service', true)
v196:CreateToggle({
	Name = 'Enable AutoEvent [Space Gym]',
	Info = 'Completes event for you',
	CurrentValue = v14.AutoEvent1,
	Callback = function(p230)
		u13.AutoEvent1 = p230
		u8:createNotice(string.format('[Event] - %s', tostring(p230)), 'Green')
	end
})
v196:CreateToggle({
	Name = 'Enable AutoEvent [Beach Gym]',
	Info = 'Completes event for you',
	CurrentValue = v14.AutoEvent2,
	Callback = function(p231)
		u13.AutoEvent2 = p231
		u8:createNotice(string.format('[Event] - %s', tostring(p231)), 'Green')
	end
})
local u232 = v196:CreateSection('Event Eggs: x0', true)
v196:CreateToggle({
	Name = 'AutoHatch Event Egg',
	Info = 'Hatches Event Egg for you.',
	CurrentValue = v14.AutoEggEvent,
	Callback = function(p233)
		u13.AutoEggEvent = p233
		u8:createNotice(string.format('[Event Hatch] - %s', tostring(p233)), 'Green')
	end
})
v196:CreateDropdown({
	Name = 'Select Open X [No need for passes]',
	Options = { 1, 3, 8 },
	CurrentOption = { v14.xTypeEvent },
	MultiSelection = false,
	Callback = function(p234)
		u13.xTypeEvent = p234[1]
		u8:createNotice(string.format('[Hatch Type] - %sx', p234[1]), 'Green')
	end
})
v197:CreateSection('Machines Service', true)
v197:CreateDropdown({
	Name = 'Select Rarity',
	Options = v21,
	CurrentOption = v14.Machine_Rarities,
	MultiSelection = true,
	Callback = function(p235)
		u13.Machine_Rarities = p235
		local v236, v237, v238 = pairs(p235)
		local v239 = ''
		while true do
			local v240
			v238, v240 = v236(v237, v238)
			if v238 == nil then
				break
			end
			v239 = v240 .. ',' .. v239
		end
		u8:createNotice(string.format('[Selected Rarities] - %s', v239), 'Green')
	end
})
v197:CreateSlider({
	Name = 'Convert Pet(s)',
	Info = 'Select how many pets to convert.',
	Range = { 1, 5 },
	Increment = 1,
	Suffix = 'Pets',
	CurrentValue = v14.Machine_Amount,
	Flag = 'Slider351367',
	Callback = function(p241)
		u13.Machine_Amount = p241
		u8:createNotice(string.format('[Pets Selected] - %s Pets', tostring(p241)), 'Green')
	end
})
v197:CreateToggle({
	Name = 'AutoConvert [Golden]',
	Info = 'Converts pets into Golden!',
	CurrentValue = v14.AutoGolden,
	Callback = function(p242)
		u13.AutoGolden = p242
		u8:createNotice(string.format('[AutoConvertor - Golden] - %s', tostring(p242)), 'Green')
	end
})
v198:CreateSection('Webhook Service', true)
if string.len(v14.Webhook_URL) > 6 then
	u13.Webhook_URL = v14.Webhook_URL
end
v198:CreateInput({
	Name = 'Webhook URL [STATISTICS]',
	Info = 'Input your webhook url',
	PlaceholderText = 'Get your URL throw discord.',
	OnEnter = false,
	RemoveTextAfterFocusLost = false,
	Callback = function(p243)
		u13.Webhook_URL = p243
		u8:createNotice(string.format('[Webhook] - URL: %s', tostring(Value)), 'Green')
	end
})
v198:CreateSlider({
	Name = 'Delay | Minutes',
	Info = 'Delay between Sendings Webhook',
	Range = { 0, 60 },
	Increment = 0.1,
	Suffix = 'm',
	CurrentValue = v14.Send_Delay,
	Flag = 'Slider1',
	Callback = function(p244)
		u13.Send_Delay = p244 * 60
		u8:createNotice(string.format('[Delay Selected] - %s m', p244), 'Green')
	end
})
v198:CreateToggle({
	Name = 'Enable Webhook Statistics',
	Info = 'Sends statistics to your Server',
	CurrentValue = v14.Send_Webhook,
	Callback = function(p245)
		u13.Send_Webhook = p245
		u8:createNotice(string.format('[Webhook] - %s', tostring(p245)), 'Green')
	end
})
v198:CreateSection('Pets Notifier Service', true)
if string.len(v14.Pet_Webhook) > 6 then
	u13.Pet_Webhook = v14.Pet_Webhook
end
v198:CreateInput({
	Name = 'Webhook URL [PETS]',
	Info = 'Input your webhook url',
	PlaceholderText = 'Get your URL throw discord.',
	OnEnter = false,
	RemoveTextAfterFocusLost = false,
	Callback = function(p246)
		u13.Pet_Webhook = p246
		u8:createNotice(string.format('[Webhook] - URL: %s', tostring(Value)), 'Green')
	end
})
v198:CreateDropdown({
	Name = 'Select Rarity',
	Options = v21,
	CurrentOption = v14.Pet_Rarities,
	MultiSelection = true,
	Callback = function(p247)
		u13.Pet_Rarities = p247
		local v248, v249, v250 = pairs(p247)
		local v251 = ''
		while true do
			local v252
			v250, v252 = v248(v249, v250)
			if v250 == nil then
				break
			end
			v251 = v252 .. ',' .. v251
		end
		u8:createNotice(string.format('[Selected Rarities] - %s', v251), 'Green')
	end
})
v198:CreateToggle({
	Name = 'Enable Webhook Pets',
	Info = 'Sends Pets to your Server',
	CurrentValue = v14.Pet_Send,
	Callback = function(p253)
		u13.Pet_Send = p253
		u8:createNotice(string.format('[Webhook] - %s', tostring(p253)), 'Green')
	end
})
local v142 = v14
task.spawn(function()
	while task.wait() do
		if v142.AutoTrain and not v142.AutoArmWrestle then
			knit.Services.ToolService.RE.onClick:FireServer()
		end
	end
end)
task.spawn(function()
	while task.wait() do
		if v142.AutoGolden then
			u15.ConvertToGold()
		end
	end
end)
task.spawn(function()
	while task.wait() do
		if v142.AutoEggEvent then
			u15.OpenEvent(v142.xTypeEvent)
		end
	end
end)
task.spawn(function()
	while task.wait() do
		if v142.AutoEvent1 or v142.AutoEvent2 then
			if v142.AutoEvent1 and v142.AutoEvent2 then
				v142.AutoEvent1 = false
				v142.AutoEvent2 = false
				u8:createNotice(string.format('[Error] - Only 1 event can be farmed!'), 'Red')
				task.wait(3)
			elseif v142.AutoEvent1 then
				u15.FarmEvent('Space')
			else
				u15.FarmEvent('Beach')
			end
		end
	end
end)
task.spawn(function()
	while task.wait() do
		if v142.AutoRebirth then
			u15.Rebirth()
		end
	end
end)
task.spawn(function()
	while task.wait() do
		if v142.AutoSpin then
			u15.SpinWheel()
		end
	end
end)
task.spawn(function()
	while task.wait() do
		if v142.AutoArmWrestle then
			u15.ArmWrestling(v142.SelectedNPC)
		end
	end
end)
task.spawn(function()
	while task.wait() do
		if v142.AutoGifts then
			u15.ClaimGifts()
		end
	end
end)
task.spawn(function()
	while task.wait() do
		if v142.AutoEggs then
			task.wait(v142.HatchDelay)
			u15.OpenEgg()
		end
	end
end)
task.spawn(function()
	while task.wait() do
		if v142.AutoDelete then
			u15.DeletePet(u15.FilterPets())
		end
	end
end)
task.spawn(function()
	while task.wait(v142.Send_Delay) do
		if v142.Send_Webhook then
			if v142.Webhook_URL == '' then
				u8:createNotice('[Webhook] - Enter Webhook URL first.', 'Red')
				task.wait(2.5)
			else
				u15.SendStatistics()
			end
		end
		v142.Statistics = u15.GetStats()
	end
end)
task.spawn(function()
	while task.wait() do
		u226:Set(u15.SetRebirths())
		u232:Set(u15.SetEventEggs())
		u125 = tick()
		task.wait(math.random(1.15, 2.3))
	end
end)
task.spawn(function()
	while task.wait(0.25) do
		local httpService2 = httpService
		writefile(u12, httpService2:JSONEncode(v142))
	end
end)
task.spawn(function()
	while task.wait(2.5) do
		if v142.AutoLeague then
			u15.FarmLeague()
		end
	end
end)
u8:createNotice(string.format('[ShinyTool] ~ Loaded in %.3f seconds.', tick() - v2), 'Gold')
local virtualUser = game:GetService('VirtualUser')
game:GetService('Players').LocalPlayer.Idled:connect(function()
	virtualUser:Button2Down(Vector2.new(0, 0), workspace.CurrentCamera.CFrame)
	wait(1)
	virtualUser:Button2Up(Vector2.new(0, 0), workspace.CurrentCamera.CFrame)
end)
u8:createNotice('[AntiAFK] ~ Enabled', 'Gold')